const RESTAURANT = {
  GET_RESTAURANTS: "GET_RESTAURANTS",
  GET_RESTAURANTS_SUCCESS: "GET_RESTAURANTS_SUCCESS",
  GET_RESTAURANTS_FAIL: "GET_RESTAURANTS_FAIL",
  SET_SELECTED_RESTAURANT: "SET_SELECTED_RESTAURANT",
};

export default RESTAURANT;
